### ISSUE TITLE
key

### ISSUE THREAD

**Issue by 89z** [bgraymusic/bgm-nerdrock#1]
Can you please clarify where you got this key:

https://github.com/bgraymusic/bgm-nerdrock/blob/422c30d6527a0f3bf38dcefd6228c9a1782e3b8b/web/js/bandcamp%20copy.js#L4

**Comment by bgraymusic** [comment]
A long time ago, Bandcamp supported a direct API to get artists/album/track info. 7 years ago they were already transitioning to a new API, but in response to a support request were able to issue me this key. I have strictly followed their ToS, using it only for myself, rate limiting (I use a cache that refreshes no more than once every 5 minutes), and – I thought – being careful not to disclose it. You can try to get your own on [their request page](https://bandcamp.com/contact?subj=API%20Access). Ask for a key to their old API that provides album and track data.

Clearly it has leaked in this file, which should never have been committed. I have now deleted it, and would appreciate your taking the key out of the readme.md file in your 2021-09-06 research folder. If it remains discoverable, I'll be ethically bound to contact Bandcamp to get it de-authorized and reissued, and who knows whether or not they'll choose simply to pull the plug on my access, taking down my web site. I appreciate your consideration.

**Comment by 89z** [comment]
Thanks for the information, but until I can get reliable programmatic access to BandCamp, Im not getting rid of any keys, including yours. Contact who you want, I dont care. Bandcamp currently uses an obfuscated Java algorithm to secure Android API requests, so I dont have any sympathy there. Thanks again for the info.

**Comment by 89z** [comment]
I think I found a workaround for this. You can make a request like this:

~~~
HEAD /track/amaris-2 HTTP/1.1
Host: schnaussandmunk.bandcamp.com
~~~

and in the response should be this:

~~~
Set-Cookie: session=1 r:["nilZ0t2809477874x1633448962"]	t:1633448962; domain=.bandcamp.com; path=/; expires=Fri, 19 Nov 2021 15:49:22 -0000
~~~

In this case, `t` is the `tralbum_type` and `2809477874` is the `tralbum_id`.
You can then try a request like this:

<http://bandcamp.com/api/mobile/24/tralbum_details?tralbum_type=t&tralbum_id=2809477874>

which will return error:

~~~
{"error_message":"band_id required","error":true}
~~~

You can fix it by just adding `band_id=1`:

<http://bandcamp.com/api/mobile/24/tralbum_details?band_id=1&tralbum_type=t&tralbum_id=2809477874>

No key needed!

**Comment by 89z** [comment]
All four keys I had found have been invalidated, so looks like you win!
